defaults:
  - ./format/test_sample_v1@_here_
  - _self_

name: "Sample Set v1 - Test8 Dataset"
output: test8/{sequence_name}/frame{index:04d}.png
reference: sampleset_v1/ref/test8/{sequence_name}/frame{index:04d}.png
metrics: test8/{sequence_name}.json
warmup: 16

data_remote: https://neural-partitioning-pyramids.mpi-inf.mpg.de/data/

src:
  sequences:
    - name: bistro1
      frames: 160
    - name: bistro2
      frames: 160
    - name: bistro3
      frames: 160
    - name: bistro1-day
      frames: 160
    - name: bistro2-day
      frames: 160
    - name: measure7
      frames: 160
    
    - name: bedroom
      frames: 80
    - name: dining-room
      frames: 80
    - name: kitchen
      frames: 80
  
  samples: 8
  rendering_height: 1080
  rendering_width: 1920
  files: sampleset_v1/test8/{sequence_name}/frame{index:04d}.zip

_target_: ${.loaders[${.framework}]}